osx_image: xcode10
language: objective-c

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES  -destination 'platform=iOS Simulator,name=iPhone 8' -scheme DependencyManager -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
